//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork325.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class custom
    {
        public int Id { get; set; }
        [DisplayName("姓名")]
        public string cName { get; set; }
        [DisplayName("等級")]
        public short cCard { get; set; }
        [DisplayName("帳號")]
        public string cAccount { get; set; }
        [DisplayName("密碼")]
        public string cPasswd { get; set; }
    }
}
